### ISSUE TITLE
issues launching a preview in https://binder-preview.conp.cloud/

### ISSUE THREAD

**Issue by arokem** [neurolibre/terraform-binderhub#5]
I am seeing this: 

<img width="1624" alt="Screenshot 2024-11-06 at 2 05 02 PM" src="https://github.com/user-attachments/assets/fa75f88d-1204-4e06-9c50-71ad277de8fd">

and eventually it times out. This doesn't seem intermittent: I've been seeing it yesterday and today several times.

**Comment by agahkarakuzu** [comment]
@arokem this looks like a temporary problem with the cloud backend, I'll check it and let you know.

**Comment by agahkarakuzu** [comment]
@arokem the issue should have been fixed now.  Can you please try and let me know? 

The problem was because  of a missing directory binding, which left the mount stale after a soft reboot performed by the provider during maintenance. Sorry about that :)

Also, there was a big migration of the infrastructure in parallel to the development of new features. These issues you are experiencing are due to these changes, thank you so much for helping us find them!

**Comment by arokem** [comment]
Confirmed that this works now. Thanks!
